SEMANTIC_ROLES = [
    "identifier",
    "entity",
    "categorical_dimension",
    "ordinal_dimension",
    "boolean",
    "numeric_measure",
    "currency_measure",
    "percentage",
    "rating",
    "count",
    "quantity",
    "date",
    "datetime",
    "duration",
    "country",
    "region",
    "city",
    "geography",
    "status",
    "free_text",
    "sentiment_text",
]

