from __future__ import annotations

from learning.models import SkillSpec


def bootstrap_skill_specs() -> list[SkillSpec]:
    """Curated skill catalog derived from the deterministic expert code.

    These are not model weights and not raw training data. They are structured
    descriptions of the capabilities already encoded in the repository.
    """

    return [
        SkillSpec(
            id="filter.multi_condition.v1",
            name="Multi-condition filtering",
            description="Filter rows while preserving every explicit AND/OR condition.",
            intents=["filter", "show matching rows", "find records", "show restaurants", "having"],
            examples=[
                "show restaurants having online delivery and table booking above 3.5 rating",
                "find orders where region is north and amount above 100",
            ],
            required_semantic_roles=["entity_name", "boolean_capability", "rating_metric"],
            required_input_types=["table"],
            preconditions=["available columns must be resolvable locally"],
            supported_parameters=["filters", "logic", "limit"],
            tool="sql.filter",
            validation_rules=["all requested predicates represented", "operators compatible with datatype"],
            failure_conditions=["drop explicit conditions", "invent missing columns"],
            expected_result="A filtered row set that reflects all requested conditions.",
            post_execution_checks=["row count is non-negative", "every predicate is represented"],
            confidence=0.96,
            source_implementation="query_router._local_entity_filter_plan",
            tags=["bootstrap", "sql", "filter"],
        ),
        SkillSpec(
            id="filter.entity_search.v1",
            name="Entity search",
            description="Find rows for a named entity without brand-specific hardcoding.",
            intents=["show", "find", "search", "lookup"],
            examples=["show Pizza Hut", "show Domino's Pizza", "show McDonald's"],
            required_semantic_roles=["entity_name"],
            required_input_types=["table"],
            preconditions=["an entity-like column exists"],
            supported_parameters=["value", "column"],
            tool="sql.filter",
            validation_rules=["resolve entity against the local worksheet", "do not invent a match"],
            failure_conditions=["brand-specific special case", "hallucinated value"],
            expected_result="A filtered subset for the requested entity.",
            post_execution_checks=["entity value present in result"],
            confidence=0.95,
            source_implementation="query_router._local_entity_filter_plan",
            tags=["bootstrap", "sql", "entity"],
        ),
        SkillSpec(
            id="analytics.group_by.v1",
            name="Grouped aggregation",
            description="Aggregate a measure by one or more dimensions.",
            intents=["total", "average", "sum", "count", "group by", "by region"],
            examples=["total revenue by region", "average rating by city"],
            required_semantic_roles=["numeric_metric", "category", "geographic_area"],
            required_input_types=["table"],
            preconditions=["a grouping column and a compatible metric exist"],
            supported_parameters=["group_by", "metrics", "order_by", "limit"],
            tool="sql.group_by",
            validation_rules=["metric datatype matches aggregate", "group_by columns exist"],
            failure_conditions=["aggregate without a metric", "group by missing column"],
            expected_result="A grouped summary table.",
            post_execution_checks=["summary schema matches requested metric"],
            confidence=0.92,
            source_implementation="query_router.build_sql_from_plan",
            tags=["bootstrap", "sql", "aggregate"],
        ),
        SkillSpec(
            id="analytics.summary_statistics.v1",
            name="Summary statistics",
            description="Produce deterministic summary statistics for a dataset or subset.",
            intents=["summary", "statistics", "describe", "overview", "profile"],
            examples=["show summary statistics", "profile the dataset"],
            required_semantic_roles=["numeric_metric"],
            required_input_types=["table"],
            preconditions=["numeric data exists"],
            supported_parameters=["columns", "include_missing"],
            tool="analytics.summary",
            validation_rules=["statistics computed locally", "no raw workbook data stored"],
            failure_conditions=["send workbook values to memory", "use remote execution for stats"],
            expected_result="A safe summary of the dataset shape and numeric distribution.",
            post_execution_checks=["summary excludes raw row values"],
            confidence=0.9,
            source_implementation="main.analyze_dataframe",
            tags=["bootstrap", "analytics"],
        ),
        SkillSpec(
            id="transform.range_binning.v1",
            name="Range binning",
            description="Turn numeric values into explicit bins or bands.",
            intents=["range binning", "bucket", "band", "bin", "age group"],
            examples=["group age into 0-18, 19-35, 36+"],
            required_semantic_roles=["numeric_metric"],
            required_input_types=["table"],
            preconditions=["source column must be numeric"],
            supported_parameters=["ranges", "labels", "source_column"],
            tool="common.transformations.range_binning",
            validation_rules=["numeric source column only"],
            failure_conditions=["apply to text columns", "hide explicit ranges"],
            expected_result="A new range-binned column or transformed table.",
            post_execution_checks=["generated bins cover the input domain"],
            confidence=0.95,
            source_implementation="common.transformations.range_binning",
            tags=["bootstrap", "transformation"],
        ),
        SkillSpec(
            id="clean.boolean_normalization.v1",
            name="Boolean normalization",
            description="Normalize yes/no style columns to stable boolean values.",
            intents=["boolean normalization", "normalize yes no", "true false", "y n"],
            examples=["normalize yes no values", "convert y/n to boolean"],
            required_semantic_roles=["boolean_capability"],
            required_input_types=["table"],
            preconditions=["a boolean-like or flag-like column exists"],
            supported_parameters=["column", "mapping"],
            tool="categorization_agent._deterministic_special_mapping",
            validation_rules=["canonical boolean labels only"],
            failure_conditions=["treat text as free-form categories"],
            expected_result="A boolean-safe normalized column.",
            post_execution_checks=["values map to a canonical boolean vocabulary"],
            confidence=0.94,
            source_implementation="categorization_agent._deterministic_special_mapping",
            tags=["bootstrap", "cleaning"],
        ),
        SkillSpec(
            id="clean.gender_normalization.v1",
            name="Gender normalization",
            description="Normalize gender variants into a canonical set.",
            intents=["gender normalization", "normalize gender", "male female"],
            examples=["m f male female femalle"],
            required_semantic_roles=["category"],
            required_input_types=["table"],
            preconditions=["a gender-like column exists"],
            supported_parameters=["column", "mapping"],
            tool="categorization_agent._deterministic_special_mapping",
            validation_rules=["preserve unknown values safely"],
            failure_conditions=["drop uncommon labels without recording them"],
            expected_result="A canonical gender mapping.",
            post_execution_checks=["normalization remains reversible through the log"],
            confidence=0.9,
            source_implementation="categorization_agent._deterministic_special_mapping",
            tags=["bootstrap", "cleaning"],
        ),
        SkillSpec(
            id="clean.country_normalization.v1",
            name="Country normalization",
            description="Normalize country variants, abbreviations, and typos safely.",
            intents=["country normalization", "normalize country", "nation", "country"],
            examples=["usa", "u.s.", "united states", "uk", "india"],
            required_semantic_roles=["geographic_area"],
            required_input_types=["table"],
            preconditions=["a country-like column exists"],
            supported_parameters=["column", "mapping"],
            tool="categorization_agent._deterministic_special_mapping",
            validation_rules=["typos only when safely supported"],
            failure_conditions=["invent unsupported country aliases"],
            expected_result="A canonical country mapping.",
            post_execution_checks=["normalized values remain geographically valid"],
            confidence=0.9,
            source_implementation="categorization_agent._deterministic_special_mapping",
            tags=["bootstrap", "cleaning"],
        ),
        SkillSpec(
            id="clean.currency_normalization.v1",
            name="Currency normalization",
            description="Detect, preserve, and convert currency fields deterministically.",
            intents=["currency", "convert", "exchange", "amount", "price"],
            examples=["convert salary to INR", "normalize currency values"],
            required_semantic_roles=["currency_metric"],
            required_input_types=["table"],
            preconditions=["currency-like data exists"],
            supported_parameters=["column", "target_currency"],
            tool="currency_utils.convert_amount",
            validation_rules=["convert only explicit currency fields"],
            failure_conditions=["treat currency words as generic labels"],
            expected_result="Currency-safe normalized or converted values.",
            post_execution_checks=["currency metadata preserved"],
            confidence=0.94,
            source_implementation="currency_utils.convert_amount",
            tags=["bootstrap", "cleaning"],
        ),
        SkillSpec(
            id="clean.missing_values.v1",
            name="Missing value handling",
            description="Fill nulls using deterministic strategies.",
            intents=["fill missing", "missing values", "nulls", "impute"],
            examples=["fill missing values with mean"],
            required_semantic_roles=["numeric_metric", "category"],
            required_input_types=["table"],
            preconditions=["a missing-value strategy is requested"],
            supported_parameters=["columns", "method", "custom_value"],
            tool="data_cleaning_utils.fill_nulls",
            validation_rules=["strategy must match dtype"],
            failure_conditions=["impute with raw workbook values"],
            expected_result="Missing values handled deterministically.",
            post_execution_checks=["null counts decrease or stay stable"],
            confidence=0.91,
            source_implementation="data_cleaning_utils.fill_nulls",
            tags=["bootstrap", "cleaning"],
        ),
        SkillSpec(
            id="clean.duplicates.v1",
            name="Duplicate detection",
            description="Identify duplicated rows or columns with deterministic rules.",
            intents=["duplicate", "dedupe", "remove duplicates"],
            examples=["remove duplicate rows"],
            required_semantic_roles=["identifier", "category"],
            required_input_types=["table"],
            preconditions=["duplicate-like structure exists"],
            supported_parameters=["subset", "keep"],
            tool="common.transformations.remove_duplicates",
            validation_rules=["duplicates measured locally"],
            failure_conditions=["assume duplicates without evidence"],
            expected_result="A deduped dataset or duplicate summary.",
            post_execution_checks=["duplicate count does not increase"],
            confidence=0.9,
            source_implementation="common.transformations.remove_duplicates",
            tags=["bootstrap", "cleaning"],
        ),
        SkillSpec(
            id="schema.semantic_role_detection.v1",
            name="Semantic role detection",
            description="Infer column roles from names, dtypes, and value shapes.",
            intents=["schema", "column discovery", "role detection", "semantic roles"],
            examples=["detect the role of each column"],
            required_semantic_roles=["identifier", "category", "numeric_metric", "date"],
            required_input_types=["table"],
            preconditions=["a dataframe exists locally"],
            supported_parameters=["columns"],
            tool="schema_intelligence.service.SchemaIntelligenceService",
            validation_rules=["persist only detected roles and confidences"],
            failure_conditions=["store row-level workbook data"],
            expected_result="A ranked set of semantic roles per column.",
            post_execution_checks=["winning role confidence is stored"],
            confidence=0.95,
            source_implementation="schema_intelligence.service.SchemaIntelligenceService",
            tags=["bootstrap", "schema"],
        ),
        SkillSpec(
            id="memory.experience_reuse.v1",
            name="Experience reuse",
            description="Retrieve past successful plans and reuse them when the schema matches.",
            intents=["remember", "reuse", "similar query", "experience"],
            examples=["have we seen this query before"],
            required_semantic_roles=["category"],
            required_input_types=["table"],
            preconditions=["a prior experience exists"],
            supported_parameters=["schema_signature", "intent"],
            tool="learning.experience_store",
            validation_rules=["do not replay unsafe experiences"],
            failure_conditions=["reuse raw workbook output"],
            expected_result="A safe reusable plan or skill hint.",
            post_execution_checks=["confidence updated after feedback"],
            confidence=0.9,
            source_implementation="query_history.service.QueryHistoryService",
            tags=["bootstrap", "memory"],
        ),
        SkillSpec(
            id="privacy.safe_local_execution.v1",
            name="Privacy-safe local execution",
            description="Keep workbook values local and only persist safe summaries.",
            intents=["privacy", "local only", "safe execution"],
            examples=["keep workbook values local"],
            required_semantic_roles=["identifier"],
            required_input_types=["table"],
            preconditions=["every execution occurs locally"],
            supported_parameters=["summary_only"],
            tool="secure_excel.executor",
            validation_rules=["never store raw rows in memory"],
            failure_conditions=["log workbook values or sheet names"],
            expected_result="A privacy-preserving execution trace.",
            post_execution_checks=["experience records contain no raw cell values"],
            confidence=0.98,
            source_implementation="secure_excel.executor",
            tags=["bootstrap", "privacy"],
        ),
    ]
